vsg-dev/vsgXchange

applications/vsgconv/vsgconv.cpp
src/cpp/ReaderWriter_cpp.cpp
src/cpp/ReaderWriter_cpp.h
src/glsl/ReaderWriter_glsl.cpp
src/glsl/ReaderWriter_glsl.h
src/osg/ReaderWriter_osg.cpp
src/osg/ReaderWriter_osg.h
src/spirv/ReaderWriter_spirv.cpp
src/spirv/ReaderWriter_spirv.h
src/vsgXchange/ReaderWriter_all.cpp

Changes to match API changes to vsg::ReaderWriter

Stream readerwriter

---

applications/vsgconv/vsgconv.cpp
src/glsl/ReaderWriter_glsl.cpp
src/osg/ConvertToVsg.cpp
src/osg/GeometryUtils.cpp
src/osg/GeometryUtils.h
src/osg/ReaderWriter_osg.cpp
src/osg/SceneBuilder.cpp
src/spirv/ReaderWriter_spirv.cpp
src/vsgXchange/ShaderCompiler.cpp

Updates to build with the Vulkan interface refactor of the core VSG.

Vulkan interface refactor

---

src/CMakeLists.txt
src/assimp/ReaderWriter_assimp.cpp
src/assimp/ReaderWriter_assimp.h
src/assimp/assimp_pbr.h
src/assimp/assimp_phong.h
src/assimp/assimp_vertex.h
src/stbi/ReaderWriter_stbi.cpp
src/stbi/ReaderWriter_stbi.h
src/stbi/stb_image.h
src/vsgXchange/ReaderWriter_all.cpp

Hi Robert,
this is the initial version of an assimp importer for vsg. Texture loading is done via stbi.
vsgconv is working.

Stbi and Assimp reader

---

src/assimp/ReaderWriter_assimp.cpp
src/assimp/assimp_pbr.h
src/assimp/assimp_phong.h

- Added disney's brdf diffuse
- Improved phong shader and glTF version 1 file handling.

Improved PBR and phong shader

---

applications/vsgconv/CMakeLists.txt
src/CMakeLists.txt
src/assimp/ReaderWriter_assimp.cpp
src/dds/ReaderWriter_dds.cpp
src/dds/ReaderWriter_dds.h
src/dds/tinyddsloader.h
src/vsgXchange/ReaderWriter_all.cpp

Hi Robert,
here is my dds importer for 2D and cubemap textures.
-André

DDS import support

---

include/vsgXchange/curl.h
include/vsgXchange/freetype.h
include/vsgXchange/images.h
include/vsgXchange/models.h
src/assimp/assimp.cpp
src/assimp/assimp_fallback.cpp
src/curl/curl.cpp
src/curl/curl_fallback.cpp
src/freetype/freetype.cpp
src/freetype/freetype_fallback.cpp
src/gdal/GDAL.cpp
src/gdal/GDAL_fallback.cpp
src/osg/OSG.cpp
src/osg/OSG_fallback.cpp

for forward declared implementations.

changed std::unique_ptr<Implementation> to Implementation* 

---

src/CMakeLists.txt

Fix not setting correct project version in cmake support files

---

src/CMakeLists.txt

see https://github.com/vsg-dev/VulkanSceneGraph/issues/305

Use cmake macro vsg_add_cmake_support_files()

---

src/osg/ConvertToVsg.cpp
src/osg/ImageUtils.cpp
src/osg/OSG.cpp

Fix compilation problems when using osg 3.4

---

src/CMakeLists.txt
src/gdal/build_vars.cmake

This mr contains a fixup for https://github.com/vsg-dev/vsgXchange/pull/55

Remove duplicated cmake code to handle dependency to GDAL

---

src/ktx/libktx/filestream.c

Fix compiling with mingw32

---

CMakeLists.txt

Counterpart for https://github.com/vsg-dev/VulkanSceneGraph/pull/566

Reenable vsg_add_target_xxx feature with submodule builds

---

src/assimp/assimp.cpp

Added reading of assimp scene, node and mesh names to respective VSG objects.

---

README.md
applications/vsgconv/vsgconv.cpp
include/vsgXchange/all.h
include/vsgXchange/curl.h
include/vsgXchange/freetype.h
include/vsgXchange/images.h
include/vsgXchange/models.h
src/CMakeLists.txt
src/all/Version.h.in
src/all/all.cpp
src/assimp/assimp.cpp
src/dds/dds.cpp
src/freetype/freetype.cpp
src/gdal/GDAL.cpp
src/gdal/gdal_utils.cpp
src/gdal/meta_utils.cpp
src/ktx/ktx.cpp
src/stbi/stbi.cpp

Fixed typos in comments and variable names without changing the API.

[FIXED] typos

---

applications/vsgconv/vsgconv.cpp

- renamed input/ouput arguments
- clarified an option's parameter
- removed whitespace

Edited the vsgconv tool's 'usage' information

---

src/assimp/assimp.cpp

I'm pretty sure the comment is wrong (otherwise the 'visit' call would be missing..)

Fixed misleading comment

---

README.md

..as I always tend to forget how this is done. It's explained in the [VSG tutorial](https://vsg-dev.github.io/vsgTutorial/foundations/vsgXchange) but one would have to know about it..

Added a note in the README document on how to specify ReaderWriter specific options

---

src/assimp/SceneConverter.cpp

Just set a local variable 'const' and added an early loop exit if the thing we were looking for was found

Minor code changes

---

src/freetype/freetype.cpp

Switch info messages to debug messages in freetype.cpp

Switch freetype info messages to debug messages

---

src/gltf/SceneGraphBuilder.cpp

See for context https://github.com/vsg-dev/vsgXchange/pull/217

Set default value for vertex normal and texture coordinate
