- src/osg/ImageUtils.cpp
Hi Robert,
while compiling vsgXchange with Microsoft Visual Studio Community 2019 Version 16.7.2
the compiler generated a warning:
vsgXchange\src\osg\ImageUtils.cpp(77,60): warning C4309: '=': truncation of constant value
I think this is an actual bug (value truncated to 15 bits) but I did not check to see if the result is different after compilation.
Regards, Laurens.
> avoid truncation of "unsigned short" max to short

- src/osg/ReaderWriter_osg.h
found the declaration as struct in  src/osg/ReaderWriter_osg.h
Regards, Laurens.
> fix MSVC warning C4099: 'osg2vsg::PipelineCache': type name first seen using 'class' now seen using 'struct'

- CMakeLists.txt
- src/CMakeLists.txt
- src/dds/ReaderWriter_dds.cpp
- src/ktx/ReaderWriter_ktx.cpp
- src/ktx/ReaderWriter_ktx.h
- src/vsgXchange/ReaderWriter_all.cpp
- src/vsgXchangeConfig.cmake.in
This pull request will add ktx read support. You will need the ktx library from the [khronos group](https://github.com/KhronosGroup/KTX-Software). Only version 4 and above is supported, as version 3 is not using cmake. The 4.0.0-beta6 release is working fine.
The ktx reader supports version 1 and 2 of the ktx texture format.
-André
> KTX texture read support

- src/curl/build_vars.cmake
> cmake: correct filename case in curl build vars

- src/assimp/build_vars.cmake
- src/curl/build_vars.cmake
- src/gdal/build_vars.cmake
- src/osg/build_vars.cmake
> In shared build mode, do not add dependencies to the generated cmake support files to development packages used only locally

- src/assimp/build_vars.cmake
Workaround until https://github.com/vsg-dev/vsgXchange/issues/65 has been fixed.
> cmake: limit finding assimp to version < 5.1

- src/assimp/assimp_fallback.cpp
- src/ktx/libktx/filestream.c
The attached patches fix problems with the compilation of vsgXchange for MinGW32 found on openSUSE
> Mingw32 compile fixes

- CMakeLists.txt
- src/vsgXchangeConfig.cmake.in
This prevents client packages from finding an older version
> cmake: let the search for vsg use the same version as a dependency

- src/assimp/assimp.cpp
DXF file shows artefacts, probably due to lines and points being misinterpreted as faces.
vsgXchange doesn't yet support lines, points & text. We need to check the aiFace structure to ensure the number of vertices is 3, otherwise reject the face. This is a temporary fix until line, point support is added.
Note that it's also possible to set a configuration parameter to reject lines and points. The suggested method is preferred because later line/point support can build from it.
Tested with problematic DXF file on Kubuntu.
> Check faces for 3 vertices to reject lines and points

- src/curl/curl.cpp
Fixes the following error on Kubuntu 20.04
/home/roland/Source/vsgXchange/src/curl/curl.cpp:202:23: error: aggregate ‘std::stringstream sstr’ has incomplete type and cannot be defined
202 |     std::stringstream sstr;
> Add include to prevent errors

- include/vsgXchange/images.h
- src/stbi/stbi.cpp
For testing:
```
vsg::ref_ptr<vsg::Data> test_write_read (vsg::ref_ptr<vsg::Data> data)                                                      {                                                                 vsg::info("before=", data->dataSize());
auto stbi = vsgXchange::stbi::create();
auto options = vsg::Options::create();                        options->extensionHint = ".png";
std::stringstream stream;                                     bool writeResult = stbi->write(data, stream, options);        vsg::info("writeResult=", writeResult);                       data = {};                                                    auto obj = stbi->read(stream, options);                       vsg::info("readResult=", obj.get());                          if (obj) …
```
> [ADDED] stbi write(ostream&) support

- src/assimp/assimp.cpp
VSG_VIEW_LIGHT_DATA isn't used anymore and is cluttering up the shader set variants.
> Remove obsolete shader define

- src/assimp/assimp.cpp
The Specular Glossiness workpath was always being chosen, which was causing the rendering of most glTF models to be subtly wrong.
before:
after:
> Correctly choose metallic roughness or specular glossy

- src/assimp/assimp.cpp
Use the utility function getColor() instead of the assimp material member function. That was failing due to a data size mismatch.
Sorry for all the churn! I didn't really see what was going on when I made the first fix for metallic/roughness. The two material models seem to display correctly now:
> Now choose specular/glossiness when needed

- src/ktx/libktx/texture2.c
#141 vsgconv build error on Windows during linking with dependencies from vcpkg
> #141 vsgconv build error on Windows

- applications/vsgconv/vsgconv.cpp
- include/vsgXchange/models.h
- src/assimp/assimp.cpp
Added command line parameter --honour-empty-nodes to vsgconv to include nodes that doesn't have children or transform matrix is identity. By default old behaviour is preserved.
>  #143 vsgconv ignores empty transforms 

- applications/vsgconv/vsgconv.cpp
The vsgconv tool would fail with a confusing error message if the caller failed to specify the output_filename.
This commit adds a check for the required minimum number of argument before starting to actually parse the input arguments using the ReaderWriters and quits, emitting an appropriate error message, if that number of arguments was not specified.
Fixes #158
> Changed vsgconv to handle missing output_filename argument

- src/freetype/freetype.cpp
In MSVS, 'warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data'
> [FIXED] removed warning

- src/curl/curl_fallback.cpp
- src/freetype/freetype_fallback.cpp
Seen in MSVS
warning C4099: 'vsgXchange::freetype::Implementation': type name first seen using 'class' now seen using 'struct'
warning C4099: 'vsgXchange::curl::Implementation': type name first seen using 'class' now seen using 'struct'
> [FIXED] build warnings

- src/assimp/assimp.cpp
Make a fix to successfully pass the glTF-AlphaBlendModeTest. When importing an opaque material, it is needed to set "pbr.alphaMaskCutoff" to zero. Otherwise the default value of 0.5 would be used, which is wrong for an opaque material.
Please delete options that are not relevant.
Tested against this model: [AlphaBlendModeTest](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AlphaBlendModeTest)
> Fix to pass "Alpha Blend Mode Test"

- include/vsgXchange/models.h
- src/assimp/assimp.cpp
The vsgXchange::assimp ReaderWriter now offers the option of not embedding texture files into the generated vsg native file. This is done by setting the external_textures option to true. Note that this does not work for textures already embedded within the source model!
In addition, by suppling the external_texture_format command line option, it is possible to specify whether the stand-alone texture files should be saved in the vsg-native format (either vsgt or vsga). By dong this there is no need for the integrating application to link against vsgXchange for texture conversion.
This leverages the vsg::External object, see [this discussion](https://github.com/vsg-dev/VulkanSceneGraph/discussions/982).
One thing I am unsure about is that currently only the vsg::Image is being loaded from …
> Optional texture embedding

- src/assimp/assimp.cpp
This is more desirable than converting sRGB textures to linear in a fragment shader because the hardware performs filtering correctly.  It pairs nicely with setting up an sRGB swap target, so shaders operate only in linear shading space.
> Add option to assign SRGB format to diffuse and emissive textures

- src/assimp/SceneConverter.cpp
warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
> Fixed MSVS warning

- README.md
Adding these instructions to help Windows users out.
Building with cmake is extremely easy, and recommended! It helps with standalone and modularized builds.
> Update README.md to include Windows build instructions

- src/ktx/libktx/ktx_zstd.h
- src/ktx/libktx/ktx_zstd_errors.h
- src/ktx/libktx/texture2.c
The ktx library required libzstd symbols for interal work but was not hiding them. This caused symbol conflicts with the dynamic loader if other shared libraries loaded the system's libzstd.so.1 library.
issue #193
> Hide zstd library symbols

- src/assimp/SceneConverter.cpp
It seems that commit https://github.com/vsg-dev/vsgXchange/commit/68edd8f22af38cdd883e2cf81c1652b6031c8e94 broke the 'Optional texture embedding' (see PR https://github.com/vsg-dev/vsgXchange/pull/172) feature, so that vsgb/vsgt files created using vsgconv will (at best) not work and (at worst) lead to the loading code to crash.
For example it happened to me that I had a top-level CullNode.. the vsg::External object referenced an external texture, but its path was not set/saved (that is the actual bug introduced in the merge), so the StartID_EndID_Filename values were incorrect (an empty object with the ID=3 was created on loading), which means the the vsg::MatrixTransform node was not loaded (since the empty object with ID=3 already cached), so I ended up with a CullNode without child …
> Fixed 'Optional Texture Embedding' feature

- src/assimp/SceneConverter.cpp
I have produced some obj and stl files with Z_UP axis convention. When I import them using vsgXchange the axis convention is switched to Y_UP, resulting in them not displaying in the correct place. This has been traced to the problem outlined below.
SceneConverter attempts to determine the up axis convention of assets by searching metadata for "UpAxis". If found, the upAxis is set to the variable upAxis, which is initialised to 1 (the Assimp equivalent of Y_UP).
Success of the metadata search is determined by comparing the returned result to AI_SUCCESS.
`if (scene->mMetaData->Get("UpAxis", upAxis) == AI_SUCCESS)`
This is incorrect because Get() returns true on success and false on failure. AI_SUCCESS is defined as 0. See the code from Assimp types.h below. Note the comment near the bottom …
> Fix issue when searching metadata and comparing result with deprecated AI_SUCCESS

- src/assimp/SceneConverter.cpp
There are other AssImp shading models, but some of them aren't things the VSG's got a built-in shader for, and there's some dumbness with the available values as the list of options was originally taken from Blender back when Blender's shading models were total nonsense (e.g. Cook-Torrance was actually Blinn-Phong, Blinn-Phong had some parts of Cook-Torrance added etc.). I've therefore ignored lots of them.
Previously, the value was put into a variable, but then never read, and that only happened on the Phong path, which was more-or-less unreachable as most assimp format loaders set `AI_MATKEY_COLOR_SPECULAR` for the Phong specular colour, so it wasn't a good signal to use to decide that PBR shaders should be used.
Despite fixing a bug in vsgXchange, this might cause bugs in downstream …
> Check AssImp shading model and use it to determine when to use Phong instead of PBR

- src/dds/dds.cpp
Support for R16G16B16A16_Float and R32G32B32A32_Float formats in 2D DDS textures
This pull request is dependent on this other one
https://github.com/vsg-dev/VulkanSceneGraph/pull/1330
> R16G16B16A16_Float and R32G32B32A32_Float formats for DDS textures

- src/gdal/GDAL_fallback.cpp
Otherwise GDAL becomes a mandatory dependency.
> Add new functions to GDAL_fallback.cpp

- src/assimp/SceneConverter.cpp
`AI_MATKEY_SHININESS_STRENGTH` is meant to be a multiplier for the specular colour, not the shininess. When it's 0.5, specularity should be half as bright, not half as shiny.
I discovered this problem when I realised an FBX file with a 0.25 `SpecularFactor` field had the unmodified (except for sRGB-to-linear conversion) `SpecularColor` value in its material uniform buffer. AssImp automatically applies other factors to their colours for FBX files (e.g. multiplying `DiffuseColor` by `DiffuseFactor` before exposing it to us as `AI_MATKEY_COLOR_DIFFUSE`), but uses `AI_MATKEY_SHININESS_STRENGTH` for `SpecularFactor` and exposes `SpecularColor` directly as `AI_MATKEY_COLOR_SPECULAR`.
I've verified that AssImp is consistently using `AI_MATKEY_SHININESS_STRENGTH` to attenuate the specular colour …
> Apply shininess strength to correct parameter

- src/gdal/GDAL.cpp
Fixes the following VS 2022 compile error. I did not test other platforms.
```
...\src\gdal\GDAL.cpp(250): error C2665: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::append': no overloaded function could convert all the argument types
```
I discovered this while trying to update vcpkg to 1.1.6.
> GDAL: fix a compile error on windows (vs2022)

- src/freetype/build_vars.cmake
The freetype library was not automatically copied by cmake into a bin folder.
By using the cmake-internal nomenclature for identifying libraries (if available, hence the if/else), the process of “what do I need to copy where afterwards?” is also automatically set in motion during construction.
> Fixed a problem with non transparent use of freetype.
